version: '3.1'

networks:
  app-tier:
    driver: bridge

volumes:
  mongodb_data:
    driver: local

services:
  fix-mongodb-permissions:
    image: 'bitnami/mongodb:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - './mongodb_data:/bitnami'
  mongodb:
    image: 'bitnami/mongodb:latest'
    networks:
      - app-tier
    volumes:
      - './mongodb_data:/bitnami'
    environment:
#      - MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
#      - MONGODB_USERNAME=$MONGODB_USERNAME
#      - MONGODB_PASSWORD=$MONGODB_PASSWORD
#      - MONGODB_DATABASE=$MONGODB_DATABASE
    ports:
      - "27017:27017"
    depends_on:
      - fix-mongodb-permissions
  backend-tier:
    image: 'etherealyn/sat-backend:latest'
    build: ./srv
    networks:
      - app-tier
    ports:
      - "3000:3000"
    volumes:
      - ./videos:/videos
    environment:
      - CORS=http://$SAT_HOSTNAME:4200
      - MULTER_DEST=/videos
      - DB_HOST=mongodb
      - DB_PORT=27017
#      - DB_USERNAME=$MONGODB_USERNAME
#      - DB_PASSWORD=$MONGODB_PASSWORD
#      - DB_NAME=$MONGODB_DATABASE
    depends_on:
      - mongodb
  frontend-tier:
    image: 'etherealyn/sat-frontend:latest'
    build: ./web
    networks:
      - app-tier
    ports:
      - "4200:80"
    environment:
      - API_URL=http://$SAT_HOSTNAME:3000
    depends_on:
      - backend-tier

